### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by filgra96** [mattcone/markdown-guide-book#10]
On page 17/62, in chapter 2, at the beginning of the section "Websites", the link related to _smallvictori.es_ doesn't work.
It goes to a **Site not found** page.

**Comment by mattcone** [comment]
Thanks for reporting this. I'll get this fixed in the next release.

**Comment by mattcone** [comment]
Thanks again for reporting this — it's been fixed in https://github.com/mattcone/markdown-guide-book/commit/50c2d614a3a11ba14328d86c8e4a2c773127e4aa.

I've published [v1.1 of the book](https://github.com/mattcone/markdown-guide-book/releases/tag/v1.1) to Gumroad and Leanpub, so if you've purchased it there you can see the updates now. Amazon is still reviewing the new manuscript, but that should be published within 24 hours.
